---
- name: Setup user-only AI dev environment with virtualenv
  hosts: localhost
  connection: local

  vars:
    venv_path: "{{ ansible_env.HOME }}/first-ai"

  tasks:

    - name: Ensure ~/.local/bin is in PATH
      shell: echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc
      args:
        executable: /bin/bash

    - name: Upgrade pip (user-only)
      shell: python3 -m pip install --user --upgrade pip

    - name: Install virtualenv (user-only)
      shell: python3 -m pip install --user virtualenv

    - name: Create virtualenv in user directory
      command: python3 -m virtualenv "{{ venv_path }}"
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Install pandas and scikit-learn in virtualenv
      command: "{{ venv_path }}/bin/pip install pandas scikit-learn"

    - name: Install JupyterLab and common packages
      command: "{{ venv_path }}/bin/pip install jupyterlab ipywidgets matplotlib"

    - name: Install PyTorch (CPU only)
      command: "{{ venv_path }}/bin/pip install torch --index-url https://download.pytorch.org/whl/cpu"

    - name: Install Hugging Face Transformers
      command: "{{ venv_path }}/bin/pip install transformers"

    - name: Register Jupyter kernel for virtualenv
      command: "{{ venv_path }}/bin/python -m ipykernel install --user --name=first-ai --display-name='Python (first-ai)'"
